webserver:
  host: '127.0.0.1'
  port: '80'
database:
  host: littleGarden.sqlite
  password: ''
  username: ''
light:
  horaire:
    start: '15:00:00'
    end: '18:04:00'
  loop_delay: 5
shutup:
  start: '21:00:00'
  end: '07:00:00'
water:
  after: 5
  loop_delay: 5
  open: 10
  targeted_moister: 0.1
